[workspace]
authors = [""]
channels = ["conda-forge"]
name = "pcap"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
notebooks = {description = "Run Jupyter notebooks", cmd = "jupyter lab" , cwd = "pcap/notebooks"}

[tasks.train]
description = "Train an Isaac Gym task by its full task name"
args = [
  "task_name",
  { arg = "wandb_project", default = "pcap" },
  { arg = "wandb_entity", default = "qcr_neural_fields" },
]
cmd = "bash source/reinforcement/ige/ige_task_runner.sh task={{ task_name }} num_envs=8192 headless=True capture_video=False capture_video_freq=1500 capture_video_len=100 force_render=True wandb_project={{ wandb_project }} wandb_entity={{ wandb_entity }} wandb_activate=True"

[tasks.train-franka]
description = "Train the Franka reaching policy"
args = [
  { arg = "wandb_project", default = "franka_pcap" },
  { arg = "wandb_entity", default = "qcr_neural_fields" },
]
depends-on = [
  { task = "train", args = ["Sim2RealFrankaTreeTactileVoxelReach", "{{ wandb_project }}", "{{ wandb_entity }}"] },
]

[tasks.train-kinova]
description = "Train the Kinova reaching policy"
args = [
  { arg = "wandb_project", default = "kinova_pcap" },
  { arg = "wandb_entity", default = "qcr_neural_fields" },
]
depends-on = [
  { task = "train", args = ["Sim2RealKinovaTreeTactileVoxelReach", "{{ wandb_project }}", "{{ wandb_entity }}"] },
]

[tasks.test-franka]
description = "Test the latest Franka reaching-policy checkpoint"
cmd = "bash source/reinforcement/ige/ige_task_runner.sh task=Sim2RealFrankaTreeTactileVoxelReach test=True num_envs=1 headless=True capture_video=False force_render=True wandb_activate=False"

[tasks.test-kinova]
description = "Test the latest Kinova reaching-policy checkpoint"
cmd = "bash source/reinforcement/ige/ige_task_runner.sh task=Sim2RealKinovaTreeTactileVoxelReach test=True num_envs=1 headless=True capture_video=False force_render=True wandb_activate=False"

[activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
spot_path = "$PIXI_PROJECT_ROOT"
isaacgymenvs_path = "$PIXI_PROJECT_ROOT/isaacgymenvs/isaacgymenvs"
PYTHONPATH = "$PIXI_PROJECT_ROOT/source${PYTHONPATH:+:$PYTHONPATH}"

[dependencies]
python = "3.8.*"
numpy = "1.23.*"
jupyter = ">=1.1.1,<2"
psutil = "==5.9.0"
matplotlib = ">=3.7.3,<4"
configargparse = ">=1.7,<2"
nbstripout = ">=0.8.2,<0.9"
wandb = ">=0.16.6,<0.17"

[pypi-dependencies]
isaacgym = {path = "isaacgym/python", editable = true}
isaacgymenvs = {path = "isaacgymenvs", editable = true}
